uploads = []
generated = []

[[outputs]]
id = "ecg3m9eChk4f1fzJQCwof"
uri = "file://ParentAnalytics.txt"
type = "text"
title = "ParentAnalytics.tsx"

[[outputs]]
id = "r4P0XgAP3SNk3V-rLNRYy"
uri = "file://RedBoot_LocalStorage_Reference.txt"
type = "text"
title = "RedBoot Local Storage Reference"
