uploads = []
generated = []

[[outputs]]
id = "ecg3m9eChk4f1fzJQCwof"
uri = "file://ParentAnalytics.txt"
type = "text"
title = "ParentAnalytics.tsx"

[[outputs]]
id = "r4P0XgAP3SNk3V-rLNRYy"
uri = "file://RedBoot_LocalStorage_Reference.txt"
type = "text"
title = "RedBoot Local Storage Reference"

[[outputs]]
id = "XPgItVQBvVL2f6lc562vS"
uri = "file://full_client_export.txt"
type = "text"
title = "Client source export (all .tsx/.ts)"

[[outputs]]
id = "KMj_KQ8tWVgGuqDsgX6px"
uri = "file://full_server_export.txt"
type = "text"
title = "Server source export (all .ts)"

[[outputs]]
id = "Z5Z2zpsE1xrevqDQG2VlZ"
uri = "file://full_export.tar.gz"
type = "unspecified"
title = "Full source export (client + server)"
