// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/keyboard/KeyboardCandy.tsx": () => import("../components/mockups/keyboard/KeyboardCandy.tsx"),
  "./components/mockups/keyboard/KeyboardLavender.tsx": () => import("../components/mockups/keyboard/KeyboardLavender.tsx"),
  "./components/mockups/keyboard/PracticeWithKeyboard.tsx": () => import("../components/mockups/keyboard/PracticeWithKeyboard.tsx"),
  "./components/mockups/paywall/AbandonmentOffer.tsx": () => import("../components/mockups/paywall/AbandonmentOffer.tsx"),
  "./components/mockups/paywall/AhaMoment.tsx": () => import("../components/mockups/paywall/AhaMoment.tsx"),
  "./components/mockups/paywall/LockedAnalytics.tsx": () => import("../components/mockups/paywall/LockedAnalytics.tsx"),
  "./components/mockups/paywall/LockedFridayTest.tsx": () => import("../components/mockups/paywall/LockedFridayTest.tsx"),
  "./components/mockups/paywall/LockedPractice.tsx": () => import("../components/mockups/paywall/LockedPractice.tsx"),
  "./components/mockups/paywall/SessionStart.tsx": () => import("../components/mockups/paywall/SessionStart.tsx")
};
